function createfigure(XMatrix1, YMatrix1, ZMatrix1)
%CREATEFIGURE(XMATRIX1, YMATRIX1, ZMATRIX1)
%  XMATRIX1:  matrix of x data
%  YMATRIX1:  matrix of y data
%  ZMATRIX1:  matrix of z data

%  Auto-generated by MATLAB on 03-Dec-2018 14:04:18

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot3
plot3(XMatrix1,YMatrix1,ZMatrix1,'Parent',axes1);

% Create xlabel
xlabel('Horizontal component of blade [m]');

% Create zlabel
zlabel('Radial Positions [m]');

% Create title
title('Geometry of Airfoil with respect to Every Radial Position of the Blade');

% Create ylabel
ylabel('Vertical component of blade [m]');

view(axes1,[0.100000000000001 90]);
